[package]
name = "rjwt-py"
version = "0.2.0"
edition = "2024"
authors = ["code@tinychain.net"]
description = "Python bindings for rjwt crate"
license = "Apache-2.0"
repository = "https://github.com/haydnv/rjwt.git"

keywords = ["jwt", "recursive", "oauth", "token", "scope"]
categories = ["authentication", "web-programming"]

[lib]
name = "rjwt"
crate-type = ["cdylib", "rlib"]

[features]
default = ["falcon"]
falcon = ["rjwt/falcon"]

[dependencies]
rjwt = { version = "0.8" }
pyo3 = { version = "0.26", features = ["extension-module"] }
pyo3-stub-gen = "0.22"
pyo3-stub-gen-derive = "0.22"
pyo3-async-runtimes = { version = "0.26", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["full"] }
ed25519-dalek = "2.1"
hr-id = { path = "../../hr-id", version = "0.7", features = ["serde"] }
pathlink = { path = "../../pathlink", version = "0.5", features = ["serialize"] }
umask = "2.1"
serde = { version = "1", features = ["derive"] }
